/**
 * Landing Page — FitCompanion
 * The public hero page shown to unauthenticated visitors.
 * Redirects authenticated users to /dashboard via middleware.
 */

import Link from 'next/link'
import { AuroraBackground } from '@/components/layout/AuroraBackground'
import {
  Zap, Dumbbell, Apple, BookOpen, TrendingUp, Flame,
  ArrowRight, Sparkles, CheckCircle2, Star
} from 'lucide-react'

// ─── Feature Data ──────────────────────────────────────────────────────────────

const features = [
  {
    icon: Sparkles,
    title: 'AI Coach',
    description: 'Get personalized diet and workout plans generated by AI — tailored to your goals, fitness level, and dietary preferences.',
    color: 'text-brand-400',
    glow: 'rgba(124, 58, 237, 0.3)',
  },
  {
    icon: Apple,
    title: 'Smart Nutrition',
    description: 'Track calories and macros with our curated Indian food database. Works with hostel mess food, canteen snacks, and home-cooked meals.',
    color: 'text-success',
    glow: 'rgba(16, 185, 129, 0.3)',
  },
  {
    icon: Dumbbell,
    title: 'Workout Planner',
    description: 'Auto-generated weekly workout plans for gym, home, or no equipment. Adjusts intensity during exam season.',
    color: 'text-info',
    glow: 'rgba(59, 130, 246, 0.3)',
  },
  {
    icon: BookOpen,
    title: 'Exam Mode',
    description: 'Finals week? Switch to Exam Mode for brain-boosting nutrition plans, 15-minute micro-workouts, and stress management.',
    color: 'text-warning',
    glow: 'rgba(245, 158, 11, 0.3)',
  },
  {
    icon: TrendingUp,
    title: 'Progress Analytics',
    description: 'Beautiful charts track your weight, calories, workouts, and hydration. See your transformation in real-time.',
    color: 'text-macro-protein',
    glow: 'rgba(244, 114, 182, 0.3)',
  },
  {
    icon: Flame,
    title: 'Streak System',
    description: 'Stay consistent with daily streaks for logging meals, completing workouts, and hitting hydration goals.',
    color: 'text-orange-400',
    glow: 'rgba(251, 146, 60, 0.3)',
  },
]

const modes = [
  { icon: '🏠', label: 'Hostel Mode', desc: 'Mess-friendly meal plans within budget' },
  { icon: '📚', label: 'Exam Mode', desc: 'Study + fitness balance during exams' },
  { icon: '🏋️', label: 'Gym Mode', desc: 'Equipment-specific workout programs' },
  { icon: '🌱', label: 'Beginner Mode', desc: 'Start from scratch with guided plans' },
]

const stats = [
  { value: '10,000+', label: 'Food items in DB' },
  { value: '35+', label: 'Exercise types' },
  { value: '100%', label: 'Free for students' },
  { value: '< 2min', label: 'Setup time' },
]

// ─── Landing Page ──────────────────────────────────────────────────────────────

export default function LandingPage() {
  return (
    <div className="relative min-h-screen overflow-x-hidden">
      {/* Aurora background */}
      <AuroraBackground intense />

      {/* ─── Navigation ─────────────────────────────────────────────────────── */}
      <nav className="relative z-10 flex items-center justify-between px-6 py-4 lg:px-12">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2 group">
          <div
            className="w-8 h-8 rounded-xl bg-gradient-brand flex items-center justify-center shadow-lg"
            style={{ boxShadow: '0 0 20px rgba(124, 58, 237, 0.5)' }}
          >
            <Zap className="w-4 h-4 text-white" strokeWidth={2.5} />
          </div>
          <span className="font-display font-700 text-lg text-foreground tracking-tight">
            FitCompanion
          </span>
        </Link>

        {/* Nav links — hidden on mobile */}
        <div className="hidden md:flex items-center gap-8">
          {['Features', 'How It Works', 'About'].map((link) => (
            <a
              key={link}
              href={`#${link.toLowerCase().replace(' ', '-')}`}
              className="text-sm text-muted-foreground hover:text-foreground transition-colors duration-200"
            >
              {link}
            </a>
          ))}
        </div>

        {/* CTA buttons */}
        <div className="flex items-center gap-3">
          <Link
            href="/auth/login"
            className="hidden sm:block text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            Sign In
          </Link>
          <Link
            href="/auth/register"
            className="flex items-center gap-1.5 px-4 py-2 rounded-full bg-gradient-brand text-white text-sm font-medium transition-all duration-200 hover:opacity-90 hover:scale-105"
            style={{ boxShadow: '0 0 20px rgba(124, 58, 237, 0.4)' }}
          >
            Get Started Free
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </nav>

      {/* ─── Hero Section ──────────────────────────────────────────────────── */}
      <section className="relative z-10 flex flex-col items-center text-center px-6 pt-16 pb-24 lg:pt-24">
        {/* Mode badges */}
        <div className="flex flex-wrap justify-center gap-2 mb-8">
          {modes.map((mode) => (
            <span
              key={mode.label}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium glass border border-white/10 text-muted-foreground"
            >
              <span>{mode.icon}</span>
              {mode.label}
            </span>
          ))}
        </div>

        {/* Heading */}
        <h1 className="font-display font-extrabold text-4xl sm:text-5xl lg:text-6xl xl:text-7xl leading-tight tracking-tight text-foreground max-w-4xl">
          Your AI Fitness Coach{' '}
          <span className="text-gradient-brand block sm:inline">
            for College Life
          </span>
        </h1>

        {/* Subtitle */}
        <p className="mt-6 text-base sm:text-lg text-muted-foreground max-w-xl leading-relaxed">
          Built for hostel students, exam seasons, and real student life.
          Get personalized diet plans, workout routines, and AI coaching —
          all completely free.
        </p>

        {/* CTAs */}
        <div className="mt-10 flex flex-col sm:flex-row items-center gap-4">
          <Link
            href="/auth/register"
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-3.5 rounded-full bg-gradient-brand text-white font-semibold text-sm transition-all duration-200 hover:opacity-90 hover:scale-105"
            style={{ boxShadow: '0 0 30px rgba(124, 58, 237, 0.5)' }}
          >
            <Sparkles className="w-4 h-4" />
            Start Your Journey — Free
          </Link>
          <Link
            href="#features"
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-3.5 rounded-full glass border border-white/10 text-foreground font-medium text-sm transition-all duration-200 hover:border-white/20 hover:bg-white/5"
          >
            See How It Works
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        {/* Trust signals */}
        <div className="mt-8 flex items-center gap-2 text-xs text-muted-foreground">
          <CheckCircle2 className="w-3.5 h-3.5 text-success" />
          <span>No credit card required</span>
          <span className="mx-2 opacity-30">·</span>
          <CheckCircle2 className="w-3.5 h-3.5 text-success" />
          <span>100% free for students</span>
          <span className="mx-2 opacity-30">·</span>
          <CheckCircle2 className="w-3.5 h-3.5 text-success" />
          <span>Set up in 2 minutes</span>
        </div>

        {/* Stats row */}
        <div className="mt-16 grid grid-cols-2 sm:grid-cols-4 gap-4 w-full max-w-2xl">
          {stats.map((stat) => (
            <div
              key={stat.label}
              className="glass rounded-2xl p-4 border border-white/8 text-center"
            >
              <div className="font-display font-bold text-2xl text-gradient-brand">
                {stat.value}
              </div>
              <div className="text-xs text-muted-foreground mt-1">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Features Grid ─────────────────────────────────────────────────── */}
      <section id="features" className="relative z-10 px-6 pb-24 lg:px-12">
        <div className="max-w-6xl mx-auto">
          {/* Section header */}
          <div className="text-center mb-12">
            <h2 className="font-display font-bold text-3xl sm:text-4xl text-foreground">
              Everything you need to{' '}
              <span className="text-gradient-brand">get fit</span>
            </h2>
            <p className="mt-3 text-muted-foreground max-w-lg mx-auto">
              Designed specifically for the college lifestyle — not a generic fitness app.
            </p>
          </div>

          {/* Feature cards grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="glass rounded-2xl p-6 border border-white/8 group transition-all duration-300 hover:border-white/15 hover:-translate-y-1"
                style={{
                  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                }}
              >
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center mb-4"
                  style={{ background: `${feature.glow}20` }}
                >
                  <feature.icon className={`w-5 h-5 ${feature.color}`} />
                </div>
                <h3 className="font-display font-semibold text-lg text-foreground mb-2">
                  {feature.title}
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA Section ───────────────────────────────────────────────────── */}
      <section className="relative z-10 px-6 pb-24 lg:px-12">
        <div className="max-w-3xl mx-auto">
          <div
            className="glass rounded-3xl p-8 sm:p-12 border border-white/10 text-center"
            style={{ background: 'rgba(124, 58, 237, 0.08)' }}
          >
            <div className="flex justify-center mb-4">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className="w-5 h-5 text-warning fill-warning" />
              ))}
            </div>
            <h2 className="font-display font-bold text-2xl sm:text-3xl text-foreground mb-3">
              Built for students who want real results
            </h2>
            <p className="text-muted-foreground mb-8 max-w-md mx-auto">
              Join thousands of college students tracking their fitness with
              India&apos;s first AI fitness platform built specifically for hostel life.
            </p>
            <Link
              href="/auth/register"
              className="inline-flex items-center gap-2 px-8 py-3.5 rounded-full bg-gradient-brand text-white font-semibold text-sm transition-all duration-200 hover:opacity-90 hover:scale-105"
              style={{ boxShadow: '0 0 30px rgba(124, 58, 237, 0.5)' }}
            >
              <Sparkles className="w-4 h-4" />
              Start Free Today
            </Link>
          </div>
        </div>
      </section>

      {/* ─── Footer ────────────────────────────────────────────────────────── */}
      <footer className="relative z-10 border-t border-white/5 px-6 py-8 lg:px-12">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-brand flex items-center justify-center">
              <Zap className="w-3 h-3 text-white" strokeWidth={2.5} />
            </div>
            <span className="font-display font-semibold text-sm text-foreground">
              FitCompanion
            </span>
          </div>
          <p className="text-xs text-muted-foreground">
            © 2026 FitCompanion. Built for students, by students.
          </p>
          <div className="flex gap-4">
            {['Privacy', 'Terms', 'Contact'].map((link) => (
              <a
                key={link}
                href="#"
                className="text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                {link}
              </a>
            ))}
          </div>
        </div>
      </footer>
    </div>
  )
}
